### ISSUE TITLE
DeepSig could not be executed! Please make sure DeepSig is installed and executable 

### ISSUE THREAD

**Issue by daisy238** [oschwengers/bakta#273] opened 2024-02-27 13:26 UTC
Hello, I've installed Bakta using Conda with Python 3.8. Deepsig has been installed but I still have the Deepsig error:

```
> bakta --db /home/bakta/db --genus klebsiella --gram - --threads 8 -v --o genome_238_bakta genome_238.fasta
> ERROR: DeepSig could not be executed! Please make sure DeepSig is installed and executable or skip requiring workflow steps via via '--gram ?'.
```

Packages installed in the conda environment are:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_tflow_select             2.3.0                       mkl  
about-time                4.2.1              pyhd8ed1ab_0    conda-forge
absl-py                   2.1.0              pyhd8ed1ab_0    conda-forge
alive-progress            3.0.1              pyhd8ed1ab_0    conda-forge
aragorn                   1.2.41               h031d066_1    bioconda
archspec                  0.2.2              pyhd8ed1ab_0    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
bakta                     1.9.2              pyhdfd78af_0    bioconda
biopython                 1.78             py38h7f8727e_0    anaconda
blast                     2.14.0               h7d5a4b4_1    bioconda
brotli-python             1.0.9            py38h6a678d5_7    anaconda
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.21.0               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py38h5eee18b_0    anaconda
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
circos                    0.69.9               hdfd78af_0    bioconda
curl                      8.4.0                hca28451_0    conda-forge
deepsig                   1.2.5              pyhdfd78af_0    bioconda
diamond                   2.1.8                h43eeafb_0    bioconda
entrez-direct             16.2                 he881be0_1    bioconda
expat                     2.5.0                hcb278e6_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gast                      0.3.3                      py_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h0b41bf4_3    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grapheme                  0.6.0              pyhd8ed1ab_0    conda-forge
grpcio                    1.59.3           py38h94a1851_0    conda-forge
h5py                      2.10.0          nompi_py38h513d04c_102    conda-forge
hdf5                      1.10.5          nompi_h5b725eb_1114    conda-forge
hmmer                     3.3.2                hdbdd923_4    bioconda
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
infernal                  1.1.4           pl5321h031d066_4    bioconda
isa-l                     2.30.0               hd590300_6    conda-forge
keras                     2.4.3              pyhd8ed1ab_0    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230802.1      cxx17_h59595ed_0    conda-forge
libblas                   3.9.0           19_linux64_openblas    conda-forge
libcblas                  3.9.0           19_linux64_openblas    conda-forge
libcurl                   8.4.0                hca28451_0    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgd                     2.3.3                h119a65a_9    conda-forge
libgfortran-ng            13.2.0               h69a702a_2    conda-forge
libgfortran5              13.2.0               ha4646dd_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libgrpc                   1.59.3               hd6c4280_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           19_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.24          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               4.24.4               hf27288f_0    conda-forge
libre2-11                 2023.06.02           h7a70373_0    conda-forge
libsqlite                 3.44.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libtiff                   4.6.0                ha9c0a0a_2    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp                   1.3.2                h658648e_1    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
markdown                  3.5.2              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5            py38h01eb140_0    conda-forge
ncbi-amrfinderplus        3.11.26              h283d18e_0    bioconda
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.24.4           py38h59b608b_0    conda-forge
openssl                   3.2.1                hd590300_0    conda-forge
opt_einsum                3.3.0              pyhc1e730c_2    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pbzip2                    1.1.13               h1fcc475_2    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          4_hd590300_perl5    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-b-cow                0.007           pl5321h166bdaf_0    conda-forge
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-clone                0.46            pl5321h166bdaf_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h166bdaf_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h166bdaf_0    conda-forge
perl-config-general       2.65            pl5321hdfd78af_0    bioconda
perl-digest-perl-md5      1.9             pl5321hdfd78af_2    bioconda
perl-encode               3.19            pl5321h166bdaf_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-config      0.008           pl5321ha770c72_0    conda-forge
perl-extutils-helpers     0.026           pl5321ha770c72_0    conda-forge
perl-extutils-installpaths 0.012           pl5321ha770c72_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-extutils-pl2bat      0.005           pl5321ha770c72_0    conda-forge
perl-font-ttf             1.06            pl5321hdfd78af_1    bioconda
perl-gd                   2.76            pl5321h5b5514e_1    bioconda
perl-inc-latest           0.500           pl5321ha770c72_0    conda-forge
perl-io-compress          2.201           pl5321hdbdd923_2    bioconda
perl-io-string            1.08            pl5321hdfd78af_4    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321h4ac6f70_6    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321h031d066_2    bioconda
perl-math-bezier          0.01            pl5321hdfd78af_2    bioconda
perl-math-round           0.07            pl5321ha770c72_0    conda-forge
perl-math-vecstat         0.08            pl5321hdfd78af_2    bioconda
perl-module-build         0.4232          pl5321ha770c72_0    conda-forge
perl-module-build-tiny    0.039           pl5321h166bdaf_0    conda-forge
perl-module-implementation 0.09            pl5321ha770c72_0    conda-forge
perl-module-runtime       0.016           pl5321ha770c72_0    conda-forge
perl-number-format        1.76            pl5321hdfd78af_0    bioconda
perl-params-validate      1.31            pl5321hec16e2b_0    bioconda
perl-parent               0.241           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h166bdaf_0    conda-forge
perl-readonly             2.05            pl5321ha770c72_0    conda-forge
perl-regexp-common        2017060201      pl5321hd8ed1ab_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h166bdaf_0    conda-forge
perl-set-intspan          1.19            pl5321hdfd78af_2    bioconda
perl-statistics-basic     1.6611          pl5321hdfd78af_3    bioconda
perl-storable             3.15            pl5321h166bdaf_0    conda-forge
perl-svg                  2.87            pl5321hd8ed1ab_0    conda-forge
perl-test-fatal           0.016           pl5321ha770c72_0    conda-forge
perl-text-format          0.62            pl5321hdfd78af_0    bioconda
perl-time-hires           1.9764          pl5321h031d066_4    bioconda
perl-try-tiny             0.31            pl5321ha770c72_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
perl-xml-parser           2.44_01         pl5321hc3e0081_1003    conda-forge
pigz                      2.8                  h2797004_0    conda-forge
piler-cr                  1.06                 h4ac6f70_4    bioconda
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
pooch                     1.8.1              pyhd8ed1ab_0    conda-forge
protobuf                  4.24.4           py38hf14ab21_0    conda-forge
psutil                    5.9.0            py38h5eee18b_0    anaconda
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyhmmer                   0.10.6           py38he5da3d1_0    bioconda
pyrodigal                 3.3.0            py38he5da3d1_0    bioconda
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.18          hd12c33a_0_cpython    conda-forge
python-isal               1.6.0            py38h01eb140_0    conda-forge
python_abi                3.8                      4_cp38    conda-forge
pyyaml                    6.0.1            py38h5eee18b_0    anaconda
re2                       2023.06.02           h2873b5e_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
scipy                     1.10.1           py38h59b608b_3    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tensorboard               2.16.2             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.7.0            py38hcdda232_1    conda-forge
tensorflow                2.2.0           mkl_py38h6d3daf0_0  
tensorflow-base           2.2.0           mkl_py38h5059a2d_0  
tensorflow-estimator      2.6.0            py38h709712a_0    conda-forge
termcolor                 2.4.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
trnascan-se               2.0.12          pl5321h031d066_0    bioconda
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.7              pyhd8ed1ab_0    conda-forge
werkzeug                  3.0.1              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0           py38h01eb140_0    conda-forge
xopen                     1.9.0            py38h578d9bd_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.19.0           py38h5eee18b_0    anaconda
zstd                      1.5.5                hfc55251_0    conda-forge
```

Any idea how I can fix this please?

**Comment by oschwengers** [comment] 2024-02-28 09:50
Hi @daisy238, this is interesting. Can you check if you can manually execute DeepSig within the activated environment?

If this is the case, could you then please execute Bakta with the `--debug` flag set and provide the log file so that I can take a deeper look into this?

**Comment by oschwengers** [comment] 2024-03-19 10:35
Hi @daisy238 , is this still active? Do you have any updates on that?

**Comment by MiSchwabe** [comment] 2024-03-26 15:56
Hi Oli,
I have the same issue. Installed bakta with mamba and installed deepsig with pi (in the environment). bakta still gives an error that deepsig is not found. "ERROR: DeepSig could not be executed! Please make sure DeepSig is installed and executable or skip requiring workflow steps via via '--gram ?'."

Any ideas how to fix it?

[PB2963EC.log](https://github.com/oschwengers/bakta/files/14761130/PB2963EC.log)

**Comment by oschwengers** [comment] 2024-03-27 13:55
Hey Michael,
thanks for the report. I guess this is not a bug in Bakta, but actually a simple dependency conflict in Mamba. DeepSig has several dependencies to pinned old Python (3.8) and Tensorflow packages. This is the reason, why I explicitly excluded DeepSig from the Bakta environment as this would hold back important updates. 

As you've shown that it is actually working,  we can exclude that this is a general issue in Bakta. Hence, I'll close this issue. I'll add a clear statement for others after closing this. Thanks again and best regards!

**Closed by oschwengers** 2024-03-27 13:55 UTC
Labels: help wanted

**Comment by oschwengers** [comment] 2024-03-27 13:57
As @MiSchwabe pointed out, this is _not_ a bug in `Bakta`, but a conflict with `DeepSig`'s Python/Tensorflow dependency versions and other Bakta dependencies.

The solution is: 
1. Create a lean fresh environment
2. Install DeepSig
3. Install Bakta
