### ISSUE TITLE
v1.8.2 error with cmscan error code: -6

### ISSUE THREAD

**Issue by jayramr** [oschwengers/bakta#238] opened 2023-09-14 15:48 UTC
Hello, 

Kindly advise how to fix below error or is this a bug? 

```
bakta --db /scratch/bakta_v2/db --output bakta/ --threads 24 input/bin.4.permissive.fa

start annotation...
predict tRNAs...
	found: 21
predict tmRNAs...
	found: 1
predict rRNAs...
Traceback (most recent call last):
  File "/scratch/.eb/2.0/software/bakta/1.8.2/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/scratch/.eb/2.0/software/bakta/1.8.2/lib/python3.10/site-packages/bakta/main.py", line 177, in main
    genome['features'][bc.FEATURE_R_RNA] = r_rna.predict_r_rnas(genome, contigs_path)
  File "/scratch/.eb/2.0/software/bakta/1.8.2/lib/python3.10/site-packages/bakta/features/r_rna.py", line 51, in predict_r_rnas
    raise Exception(f'cmscan error! error code: {proc.returncode}')
Exception: cmscan error! error code: -6
```

Thanks
Jay

**Comment by oschwengers** [comment] 2023-09-15 07:32
Hi Jay,
thanks for reporting! Seems like `cmscan` itself is crashing, so technically this is not a bug in Bakta but cmscan. However, if you execute Bakta with the `--debug` option and provide me the logs, I could take a closer look at this. If possible, you could also send me the input file so I can debug this myself.

**Comment by jayramr** [comment] 2023-09-15 07:48
Hi @oschwengers 

Here is the debug output and please find the input file. 

By the way, i downloaded the database using below command.

```
bakta_db download --output <path-to-dir>
```

```
bakta --debug  --db /scratch/Reference_Genomes/In_house/Metagenomic/bakta_v2/db --output bakta/ --threads 24 input/bin.4.permissive.fa
Bakta v1.8.2
Options and arguments:
	input: /scratch/bakta/input/bin.4.permissive.fa
	db: /scratch/bakta_v2/db, version 5.0, full
	output: /scratch/bakta/bakta
	tmp directory: /tmpdata/tmpwru4g49a
	prefix: bin.4.permissive
	threads: 24
	debug: True
	translation table: 11

Bakta runs in DEBUG mode! Temporary data will not be destroyed at: /tmpdata/tmpwru4g49a

parse genome sequences...
	imported: 146
	filtered & revised: 146
	contigs: 146

start annotation...
predict tRNAs...
	found: 21
predict tmRNAs...
	found: 1
predict rRNAs...
Traceback (most recent call last):
  File "/scratch/gencore/.eb/2.0/software/bakta/1.8.2/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/scratch/gencore/.eb/2.0/software/bakta/1.8.2/lib/python3.10/site-packages/bakta/main.py", line 177, in main
    genome['features'][bc.FEATURE_R_RNA] = r_rna.predict_r_rnas(genome, contigs_path)
  File "/scratch/gencore/.eb/2.0/software/bakta/1.8.2/lib/python3.10/site-packages/bakta/features/r_rna.py", line 51, in predict_r_rnas
    raise Exception(f'cmscan error! error code: {proc.returncode}')
Exception: cmscan error! error code: -6
```
[bin.4.permissive.fa.tgz](https://github.com/oschwengers/bakta/files/12616965/bin.4.permissive.fa.tgz)


Thanks
Jay

**Comment by oschwengers** [comment] 2023-09-15 08:16
Hi,
Unfortunately, I cannot reproduce this error using Bakta v1.8.2 on Ubuntu (fresh installation via Conda) :
```
Bakta v1.8.2
Options and arguments:
	input: <....>/test-bakta-gh-238/bin.4.permissive.fa
	db: <....>/databases/bakta/db-v5.0, version 5.0, full
	output: <....>/test-bakta-gh-238/output
	tmp directory: /tmp/tmpks6abj90
	prefix: test
	threads: 8
	debug: True
	translation table: 11

Bakta runs in DEBUG mode! Temporary data will not be destroyed at: /tmp/tmpks6abj90

parse genome sequences...
	imported: 146
	filtered & revised: 146
	contigs: 146

start annotation...
predict tRNAs...
	found: 21
predict tmRNAs...
	found: 1
predict rRNAs...
	found: 0
predict ncRNAs...
	found: 8
predict ncRNA regions...
	found: 2
predict CRISPR arrays...
	found: 0
predict & annotate CDSs...
	predicted: 1079 
	discarded spurious: 0
	revised translational exceptions: 0
	detected IPSs: 402
	found PSCs: 538
	found PSCCs: 32
	lookup annotations...
	conduct expert systems...
		amrfinder: 0
		protein sequences: 0
	combine annotations and mark hypotheticals...
	detect pseudogenes...
		pseudogene candidates: 48
		found pseudogenes: 11
analyze hypothetical proteins: 121
	detected Pfam hits: 40 
	calculated proteins statistics
	revise special cases...
extract sORF...
	potential: 12443
	discarded due to overlaps: 9989
	discarded spurious: 0
	detected IPSs: 1
	found PSCs: 0
	lookup annotations...
	filter and combine annotations...
	filtered sORFs: 1
detect gaps...
	found: 46
detect oriCs/oriVs...
	found: 0
detect oriTs...
	found: 0
apply feature overlap filters...
select features and create locus tags...
selected: 1157
improve annotations...
	revised gene symbols: 0

genome statistics:
	Genome size: 944,365 bp
	Contigs/replicons: 146
	GC: 31.2 %
	N50: 11,133
	N ratio: 0.5 %
	coding density: 81.8 %

annotation summary:
	tRNAs: 21
	tmRNAs: 1
	rRNAs: 0
	ncRNAs: 8
	ncRNA regions: 2
	CRISPR arrays: 0
	CDSs: 1078
		hypotheticals: 121
		pseudogenes: 11
		signal peptides: 0
	sORFs: 1
	gaps: 46
	oriCs/oriVs: 0
	oriTs: 0
```

**Comment by oschwengers** [comment] 2023-09-15 08:18
Could you execute Bakta using `--debug` and attach the `log` file?

**Comment by jayramr** [comment] 2023-09-15 08:33
Hi, 

in the debug logs i can see 

```
12:09:19.502 - INFO - DB - detected: major=4, minor=0, date=2022-08-25
12:09:21.192 - INFO - UTILS - dependency: tool=tRNAscan-SE, version=v2.0.9
12:09:21.248 - INFO - UTILS - dependency: tool=aragorn, version=v1.2.41
12:09:21.506 - INFO - UTILS - dependency: tool=cmscan, version=v1.1.4
12:09:21.710 - INFO - UTILS - dependency: tool=pilercr, version=v1.6.0
12:09:21.761 - INFO - UTILS - dependency: tool=prodigal, version=v2.6.3
12:09:21.816 - INFO - UTILS - dependency: tool=amrfinder, version=v3.10.40
12:09:21.833 - ERROR - UTILS - AMRFinderPlus database not installed ->>>> 
```

But  i have the database files available in 

```
ls -l ..//db/amrfinderplus-db/
drwxr-xr-x 2 user1 users 16384 Sep 14 19:38 2023-08-08.2
lrwxrwxrwx 1 user1 users    12 Sep 14 19:38 latest -> 2023-08-08.2
``

Is this not correct, could you advise how to generate/download this AMRFinderPlus DB ?

**Comment by oschwengers** [comment] 2023-09-15 08:36
Seems like you're running Bakta v1.8.2 with DB v4.0. Actually, this is strange, because, v1.8.2 requires DB v.5.0.
Could you discard the old DB and download a fresh new one via `bakta_db download --output <DEST>`

**Comment by jayramr** [comment] 2023-09-15 08:42
Hi @oschwengers 

But yesterday only i did downloaded and installed bakta 1.8.2 and not sure why the below command picked old version of DB.

Let me download it again and update you how it goes.

```
bakta_db download --output <path-to-dir>
Bakta software version: 1.8.2
Required database schema version: 5

Selected DB type: full

Fetch DB versions...
        ... compatible DB versions: 1
Download database: v5.0, type=full, 2023-02-20, DOI: 10.5281/zenodo.7669534, URL: https://zenodo.org/record/7669534/files/db.tar.gz...
```

**Comment by jayramr** [comment] 2023-09-15 08:46
Sorry, i provided the output from the wrong log file. Attached is the correct one. Please advise the debug log output atached.
[bin.4.permissive.log](https://github.com/oschwengers/bakta/files/12617491/bin.4.permissive.log)

**Comment by oschwengers** [comment] 2023-09-15 09:19
Thanks for the log.

Line 2,435 reveals the error message (STDERR) from cmscan: `Fatal exception (source file esl_threads.c, line 128): thread creation failed`

So this is certainly a bug within Infernal/cmsearch and not Bakta-related and, unfortunately, we cannot do anything about this. You might want to report this upstream to the Infernal developers: https://github.com/EddyRivasLab/infernal

I close this for now. Please do not hesitate to re-open it in any case (or reference it from the upstream cmscan repository).

**Closed by oschwengers** 2023-09-15 09:19 UTC
Labels: bug

**Comment by jayramr** [comment] 2023-09-15 09:51
I figure it out the problem. Thread is causing the problem. Now i changed to single thread no issues. Thabks for your help.
