### ISSUE TITLE
pyhmmer not found

### ISSUE THREAD

**Issue by samlipworth** [oschwengers/bakta#297] opened 2024-06-27 14:14 UTC
Hello,

Installed via conda,

ERROR: Pyhmmer could not be executed! Please make sure Pyhmmer is installed and executable or skip requiring workflow steps via via '--skip-cds --skip-sorf'.

mamba install pyhmmer tells me that it is already installed.

Any ideas?

THanks,
Sam

**Comment by oschwengers** [comment] 2024-06-27 14:53
Hi, could you run Bakta in `--debug` mode and provide the `*.log` file?

**Comment by samlipworth** [comment] 2024-06-28 09:23
[ST131_HG941718.1.log](https://github.com/user-attachments/files/16027312/ST131_HG941718.1.log)

**Comment by oschwengers** [comment] 2024-07-01 08:31
Thanks, could you please try to execute the following _within_ the Bakta conda env?

```
$ python3
>>> import pyhmmer
>>> print(pyhmmer.__version__)
```

**Comment by oschwengers** [comment] 2024-07-01 08:42
Interesting! This is the first time this is being reported and I cannot reproduce it. Have you tried to start from a fresh conda environment, just to make sure there are no side effects?

**Comment by samlipworth** [comment] 2024-07-03 09:13
deleted conda env, cleared cache, created new conda env and re-installed using conda - still getting the same error.

**Comment by kenken86** [comment] 2024-07-07 09:27
I have the same problem

**Comment by oschwengers** [comment] 2024-07-10 08:23
Thanks all for reporting. Unfortunately, I cannot reproduce this error on Ubuntu 20.4 using Mamba and creating a fresh env with Bakta 1.9.3:

```
mamba create --quiet --yes -p ./conda-env bakta=1.9.3
mamba activate ./conda-env/
bakta --db db-v5.1-light/ --skip-trna --skip-rrna --skip-ncrna --skip-ncrna-region --skip-plot --debug GCF_000008865.2.fna.gz
Bakta v1.9.3
Options and arguments:
	input: .../GCF_000008865.2.fna.gz
	db: .../db-v5.1-light, version 5.1, light
	output: .../bakta-gh-297
	tmp directory: /tmp/tmpj2ogjx7x
	prefix: GCF_000008865.2.fna
	threads: 8
	debug: True
	translation table: 11
	skip tRNA: True
	skip rRNA: True
	skip ncRNA: True
	skip ncRNA region: True
	skip plot: True

Bakta runs in DEBUG mode! Temporary data will not be destroyed at: /tmp/tmpj2ogjx7x

parse genome sequences...
...
start annotation...
...
predict & annotate CDSs...
	predicted: 5387 
	discarded spurious: 11
	revised translational exceptions: 0
	detected IPSs: 0
	found PSCCs: 4995
	lookup annotations...
	conduct expert systems...
		amrfinder: 39
		protein sequences: 792
	combine annotations and mark hypotheticals...
...
annotation summary:
	tRNAs: 0
	tmRNAs: 1
	rRNAs: 0
	ncRNAs: 0
	ncRNA regions: 0
	CRISPR arrays: 1
	CDSs: 5377
		hypotheticals: 435
		pseudogenes: 0
		signal peptides: 0
	sORFs: 19
	gaps: 0
	oriCs/oriVs: 3
	oriTs: 1
...
```

I'm a bit puzzled. Are you running Bakta on Linux or Mac?

**Comment by kenken86** [comment] 2024-07-10 18:35
Linux

**Comment by oschwengers** [comment] 2024-07-11 14:35
That's weird. I'm sorry but I can neither reproduce this error nor grasp why this could potentially happen - besides mixed-up conda environments.

**Comment by oschwengers** [comment] 2024-07-18 08:38
@samlipworth @kenken86 
I just released [v1.9.4](https://github.com/oschwengers/bakta/releases/tag/v1.9.4) with a potential fix for this issue. Could you please give it a try (best in a fresh Conda env)? Thanks!

**Comment by samlipworth** [comment] 2024-07-18 08:53
Thanks so much for your persistance - I have just installed on a fresh conda env and can confirm the problem is fixed. Look forward to using Bakta in anger!

BW,
Sam

**Comment by oschwengers** [comment] 2024-07-19 11:22
OK, I tentatively assume that this issue is fixed and thus, close this issue.

Just in case these issues remain after updating Bakta to `v1.9.4` in a fresh Conda env, @kenken86  , please do not hesitate to re-open this.

**Closed by oschwengers** 2024-07-19 11:22 UTC
Labels: bug
