### ISSUE TITLE
Bakta Diamond error

### ISSUE THREAD

**Issue by dannyionescu** [oschwengers/bakta#272] opened 2024-02-10 15:37 UTC
Hi, 
I installed Bakta recently using mamba. 
I downloaded the DB using the built-in command.

I am trying to run mamba on a series of fasta files:

for f in *fasta
do
sample=${f//.fasta/}

bakta\
 --db /project02/DATABASES/bakta/db\
 --prefix $sample\
 --output $sample.bakta\
 --threads 64\
 --tmp-dir ./tmp\
 $f

done

The program seems to start working correctly producing the following output:
parse genome sequences...
        imported: 1
        filtered & revised: 1
        contigs: 1

start annotation...
predict tRNAs...
        found: 71
predict tmRNAs...
        found: 1
predict rRNAs...
        found: 24
predict ncRNAs...
        found: 27
predict ncRNA regions...
        found: 55
predict CRISPR arrays...
        found: 2
predict & annotate CDSs...
        predicted: 4061
        discarded spurious: 0
        revised translational exceptions: 0
        detected IPSs: 13

But then it fails producing the following error:

Traceback (most recent call last):
  File "/project02/miniforge3/envs/bakta/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/project02/miniforge3/envs/bakta/lib/python3.10/site-packages/bakta/main.py", line 259, in main
    cdss_psc, cdss_pscc, cdss_not_found = psc.search(cdss_not_found)
  File "/project02/miniforge3/envs/bakta/lib/python3.10/site-packages/bakta/psc.py", line 64, in search
    raise Exception(f'diamond error! error code: {proc.returncode}')
Exception: diamond error! error code: -11

Bakta is installed for all users (by me) as root in a mamba environment. I tried to run the same command as root but I get the same error.

I ran Diamond test from the bakta environment and all tests (20/20) came back OK.

Looking forward to any tips on how to solve this.

Thanks

Danny

**Comment by oschwengers** [comment] 2024-02-12 09:46
Hi @dannyionescu, this is a known bug caused by the recent Diamond version `v2.1.9`. This has also been reported by other users (https://github.com/oschwengers/bakta/issues/271) and I just manually tested and confirmed this.

This bug is filed upstream https://github.com/bbuchfink/diamond/issues/785.
You can downgrade Diamond to `v2.1.8` which should solve the issue until this bug is fixed upstream.

**Comment by valery-shap** [comment] 2024-02-19 12:04
Hi,
I also recently installed Bakta using conda, checked the version of Diamond: it is v.2.1.8. But I still have this issue:
`Bakta v1.9.2
Options and arguments:
	input: AP006726.fasta
	db: db, version 5.1, full
	output: test_apo006726
	force: True
	tmp directory: /tmp/tmpiqh5yhpl
	prefix: apo006726_test
	threads: 4
	translation table: 11

parse genome sequences...
	imported: 1
	filtered & revised: 1
	plasmids: 1

start annotation...
predict tRNAs...
	found: 0
predict tmRNAs...
	found: 0
predict rRNAs...
	found: 0
predict ncRNAs...
	found: 1
predict ncRNA regions...
	found: 1
predict CRISPR arrays...
	found: 0
predict & annotate CDSs...
	predicted: 251 
	discarded spurious: 0
	revised translational exceptions: 0
	detected IPSs: 248
	found PSCs: 2
	found PSCCs: 0
	lookup annotations...
	conduct expert systems...
		amrfinder: 29
		protein sequences: 33
	combine annotations and mark hypotheticals...
	detect pseudogenes...
Traceback (most recent call last):
  File "/miniconda3/envs/bakta/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/main.py", line 302, in main
    pseudo_candidates = feat_cds.predict_pseudo_candidates(hypotheticals)
  File "/miniconda3/envs/bakta/lib/python3.10/site-packages/bakta/features/cds.py", line 518, in predict_pseudo_candidates
    raise Exception(f'diamond error! error code: {proc.returncode}')
Exception: diamond error! error code: 1
`
The first launch with another sample run without errors.

Best regards,
Valery

**Comment by oschwengers** [comment] 2024-03-04 10:33
FYI: I temporarily pinned Diamond to `v2.1.8` in the Bakta Bioconda package: https://github.com/bioconda/bioconda-recipes/pull/46111

**Comment by oschwengers** [comment] 2024-03-08 08:56
This bug is occurring in Diamond and it has been reported upstream. A downgrade to v2.1.8 is currently the best we can do until this is fixed.

As this isn't caused by Bakta but Diamond and can be fixed by a downgrade to `v2.1.8`, I'll close this for now. If this bug remains, please do not hesitate to re-open this or a new issue.

**Closed by oschwengers** 2024-03-08 08:56 UTC
Labels: bug
