### ISSUE TITLE
Circos plot error

### ISSUE THREAD

**Issue by Rridley7** [oschwengers/bakta#174] opened 2022-11-25 09:31 UTC
Hi, thanks for the great work on this tool, I have already found it very useful! I have run into an error with the new bakta plot feature, after calling bakta on a genome using default settings, or calling bakta_plot on a previously made json file.

Bakta was installed via mamba (conda) with `mamba install bakta`

For the case of calling bakta_plot: 
The input command:
`bakta_plot S12_1a9859_mtb_spa_t.1.json`

Returns:
```
draw circular genome plot (type=features) containing all sequences...
Traceback (most recent call last):
  File "/opt/anaconda3/envs/FA_test/bin/bakta_plot", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/FA_test/lib/python3.10/site-packages/bakta/plot.py", line 178, in main
    write_plot(features, contigs, output_path, colors, plot_type=plot_type)
  File "/opt/anaconda3/envs/FA_test/lib/python3.10/site-packages/bakta/plot.py", line 255, in write_plot
    raise Exception(f'circos error! error code: {proc.returncode}')
Exception: circos error! error code: 255
```

When run with debug flag (not sure if this is the same error): 

`bakta_plot --debug S12_1a9859_mtb_spa_t.1.json`
```
Bakta v1.6.0
Options and arguments:
	input: /Users/rodney/Data/Coding_Programs/scratch_folder/S12_1a9859_mtb_spa_t.1.json
Traceback (most recent call last):
  File "/opt/anaconda3/envs/FA_test/bin/bakta_plot", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/FA_test/lib/python3.10/site-packages/bakta/plot.py", line 150, in main
    print(f'\tconfig: {config_path}')
UnboundLocalError: local variable 'config_path' referenced before assignment
```

When run on a full genome: 
Command:
`bakta --db /storage/home/hcoda1/6/rridley3/shared3/DB/bakta/db  --debug S10_4d3374_mtb_idb_t.15.fa`
The output of this is attached, however the error is the same message as the first.

[bakta_debug.txt](https://github.com/oschwengers/bakta/files/10090363/bakta_debug.txt)

**Comment by oschwengers** [comment] 2022-11-25 11:51
Hi @Rridley7 , thanks for the report. The bug in `bakta_plot` was a simple unbound variable. It's fixed in https://github.com/oschwengers/bakta/commit/0ad59de1dbd4622179e51c0694d780a3324434b0 and will be available in the next upcoming 1.6.1 patch release. Until then: without `--verbose` or `--debug` it does not occur.

Regarding the first initial bug. It seems like this is related to Circos. To further debug this, could you provide either the Circos logs that are stored in `/tmp/tmp2gi_5r6_` or the genome itself?

**Comment by Rridley7** [comment] 2022-11-25 18:08
Genome file is attached, thanks!
[S10_4d3374_mtb_idb_t.15.fa.zip](https://github.com/oschwengers/bakta/files/10094573/S10_4d3374_mtb_idb_t.15.fa.zip)

**Comment by Proelmocan23** [comment] 2022-11-29 20:11
Hi,

I am having a difficult time understanding the output of the circular genome. Is there a legend or manual I may read up on to understand what is being plotted?  
![GCF_000020025 1_ASM2002v1_genomic](https://user-images.githubusercontent.com/115587387/204637807-29c1c1ec-4729-457b-9f6e-080e7c87471e.png)

**Comment by oschwengers** [comment] 2022-12-01 08:28
@Rridley7 The cause for this is the default value (200) of the Circos `max_ideograms` setting preventing it from creating too-crowded figures. Therefore, it fails on genomes having more than 200 contigs.

Unfortunately, I wasn't aware of this, since I only tested it on complete and "better" draft genomes. For now, please use the `--skip-plot` option to skip this step. I'll come up with a solution and patch version soon.

**Closed** 2022-12-06 16:53 UTC
Labels: bug

**Comment by augustkx** [comment] 2024-11-29 14:18
Hi, 

I am using Bakta v 1.9.4, but still come across with the erros

Traceback (most recent call last):
  File "~/miniconda3/envs/env_Bactopia/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "~/miniconda3/envs/env_Bactopia/lib/python3.8/site-packages/bakta/main.py", line 557, in main
    plot.write_plot(features, contigs, cfg.output_path)
  File "~/miniconda3/envs/env_Bactopia/lib/python3.8/site-packages/bakta/plot.py", line 260, in write_plot
    raise Exception(f'circos error! error code: {proc.returncode}')
Exception: circos error! error code: 255

**Comment by augustkx** [comment] 2024-11-29 14:20
Hi

I am using version: 1.9.4, for genomes with 1000+ contigs
But there ia still the error

> Traceback (most recent call last):
>   File "~/miniconda3/envs/env_Bactopia/bin/bakta", line 10, in <module>
>     sys.exit(main())
>   File "~/miniconda3/envs/env_Bactopia/lib/python3.8/site-packages/bakta/main.py", line 557, in main
>     plot.write_plot(features, contigs, cfg.output_path)
>   File "~/miniconda3/envs/env_Bactopia/lib/python3.8/site-packages/bakta/plot.py", line 260, in write_plot
>     raise Exception(f'circos error! error code: {proc.returncode}')
> Exception: circos error! error code: 255

**Comment by augustkx** [comment] 2024-12-02 17:54
An update:

When running bakta, I need to use "--skip-plot" to avoid the error.
Afterwards, `bakta_plot  *.json` works.
