### ISSUE TITLE
amrfinder_update with local database breaks bakta 

### ISSUE THREAD

**Issue by geboro** [oschwengers/bakta#211] opened 2023-05-05 10:29 UTC
Hello. I am having problems installing `bakta` because `amrfinder_update` cannot connect to the ftp server, similar to what was reported here: #203 , which might be related to certificate/proxy issues since the conda recipe downloads its own versions of `curl` and `openssl`.  

In any case, I figured a workaround would be to install `amrfinder` manually as follows:

1. Create a mamba environment with `amrfinder` && activate it
2. Install `bakta` in the mamba environment
3. Download the database with `bakta_download`. It will fail when trying to update the AMRfinder database
4. Manually download the AMRfinderDB and put it in the subdirectory `amrfinderplus-db` under the bakta database `/home/user/bakta/db/amrfinderplus-db`
5. Index it wiht `amrfinder_index` 
6. Run bakta with `--db` pointing to the bakta-db directory: `bakta --db /home/user/bakta/db genome.fasta`

This produced a working `amrfinder` that passed the tests suggested in its git repo, and I even ran it against my genomes successsfully (even though it didn't find any AMR genes). 

Still, when running `bakta`, it teases me with all the things it finds... until it reaches `amrfinder` and fails again:
 
```
bakta --db /home/bioinf/bioinf_archive/98_mökiDatabases/bakta/db --verbose --output ./seti_Etasmaniensis_54G_BAKTA --prefix Eta54G --locus-tag Eta54G --threads 30 Erwinia_tasmaniensis_54G.fasta 
Bakta v1.7.0
Options and arguments:
	input: /home/bioinf/bioinf_data/57_boge/Erwinia_tasmaniensis/Genomes/seti_Erwinia_tasmaniensis_54G/Erwinia_tasmaniensis_54G.fasta
	db: /home/bioinf/bioinf_archive/98_mökiDatabases/bakta/db, version 5.0, full
	output: /home/bioinf/bioinf_data/57_boge/Erwinia_tasmaniensis/Genomes/seti_Erwinia_tasmaniensis_54G/seti_Etasmaniensis_54G_BAKTA
	tmp directory: /tmp/tmp7roq2qu4
	prefix: Eta54G
	threads: 30
	translation table: 11
	locus tag prefix: Eta54G

parse genome sequences...
	imported: 4
	filtered & revised: 4
	contigs: 4

start annotation...
predict tRNAs...
	found: 83
predict tmRNAs...
	found: 1
predict rRNAs...
	found: 22
predict ncRNAs...
	found: 43
predict ncRNA regions...
	found: 45
predict CRISPR arrays...
	found: 2
predict & annotate CDSs...
	predicted: 3793 
	discarded spurious: 2
	revised translational exceptions: 0
	detected IPSs: 1615
	found PSCs: 1744
	found PSCCs: 272
	lookup annotations...
	conduct expert systems...
Traceback (most recent call last):
  File "/home/bioinf/mambaforge/envs/bakta/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/home/bioinf/mambaforge/envs/bakta/lib/python3.10/site-packages/bakta/main.py", line 269, in main
    expert_amr_found = exp_amr.search(cdss, cds_aa_path)
  File "/home/bioinf/mambaforge/envs/bakta/lib/python3.10/site-packages/bakta/expert/amrfinder.py", line 47, in search
    raise Exception(f"amrfinder error! error code: {proc.returncode}. Please, try 'amrfinder_update --force_update --database {amrfinderplus_db_path}' to update AMRFinderPlus's internal database.")
Exception: amrfinder error! error code: 1. Please, try 'amrfinder_update --force_update --database /home/bioinf/bioinf_archive/98_mökiDatabases/bakta/db/amrfinderplus-db' to update AMRFinderPlus's internal database.
```
Could it be that `bakta` needs the specific location of the `amrfinder` database? is this an option? 
Also, is there an option to skip AMR detection?
Thanks again

**Comment by oschwengers** [comment] 2023-05-11 11:19
Hi, no, there is no option to skip the AMR detection since it's part of the CDS annotation workflow. 
I think this is somehow related to AMRFinder itself or any 3rd party dependency thereof. Could you maybe try installing Bakta's db using the fresh AMRFinder release https://github.com/ncbi/amr/releases/tag/amrfinder_v3.11.14?

I don't know if this is trivial or maybe just overlooked, but in your example you have `bakta --db /home/user/bakta/db genome.fasta` but Bakta is actually pointing to `amrfinder_update --force_update --database /home/bioinf/bioinf_archive/98_mökiDatabases/bakta/db/amrfinderplus-db`.

**Comment by awh082834** [comment] 2023-06-21 17:28
I am currently having this issue as well, I have updated the database for AMRFinderPlus and its located in the correct director, within the Bakta DB directory. Here is my command. 
 `bakta --db /path/to/databases/bakta_db/ --prefix 1708_bakta --output bakta_1708_out_2 --threads 8 plasmid_AA860.fasta`

Log File:
```
17:17:59.781 - INFO - CDS - replicon cds: predicted=207
17:17:59.781 - INFO - CDS - predicted=207
17:17:59.782 - INFO - ORF - write internal aa seqs: # seqs=207, path=/tmp/tmp_pwlgdpe/cds.spurious.faa
17:18:00.214 - INFO - ORF - discarded=0
17:18:00.708 - INFO - UPS - looked-up=191
17:18:00.846 - INFO - IPS - looked-up=191
17:18:00.848 - INFO - ORF - write internal aa seqs: # seqs=16, path=/tmp/tmp_pwlgdpe/cds.psc.faa
17:25:04.524 - INFO - PSC - found: PSC=10, PSCC=2
17:25:04.750 - INFO - PSC - looked-up=202
17:25:05.041 - INFO - PSCC - looked-up=107
17:25:05.043 - INFO - ORF - write internal aa seqs: # seqs=207, path=/tmp/tmp_pwlgdpe/cds.expert.faa
17:25:05.064 - WARNING - EXPERT-AMRFINDER - AMR expert system failed! amrfinder-error-code=1
17:25:05.066 - INFO - MAIN - removed tmp dir: /tmp/tmp_pwlgdpe
```
Command Line Error:
```
predict & annotate CDSs...
	predicted: 207 
	discarded spurious: 0
	revised translational exceptions: 0
	detected IPSs: 191
	found PSCs: 10
	found PSCCs: 2
	lookup annotations...
	conduct expert systems...
Traceback (most recent call last):
  File "/home/ahale/miniconda3/bin/bakta", line 10, in <module>
    sys.exit(main())
  File "/home/ahale/miniconda3/lib/python3.7/site-packages/bakta/main.py", line 260, in main
    expert_amr_found = exp_amr.search(cdss, cds_aa_path)
  File "/home/ahale/miniconda3/lib/python3.7/site-packages/bakta/expert/amrfinder.py", line 47, in search
    raise Exception(f"amrfinder error! error code: {proc.returncode}. Please, try 'amrfinder_update --force_update --database {amrfinderplus_db_path}' to update AMRFinderPlus's internal database.")
Exception: amrfinder error! error code: 1. Please, try 'amrfinder_update --force_update --database /path/to/databases/bakta_db/amrfinderplus-db' to update AMRFinderPlus's internal database.
```

**Comment by oschwengers** [comment] 2023-08-09 08:34
@awh082834 , have you tried to download the Bakta database from scratch via `bakta_db download --output <DB_PATH>`?

You could maybe try with the `light` DB first, to speed-up this test: `bakta_db download --output <DB_PATH> --type light`

**Comment by oschwengers** [comment] 2023-08-22 13:24
FYI: I can confirm that `bakta_db download --type light` with Bakta `1.8.1` and AMRFinder `3.11.18` is working correctly.

**Comment by oschwengers** [comment] 2023-10-25 08:36
Hi, @geboro & @awh082834,
I just conducted another up-to-date round trip test in a fresh Conda environment for both Bakta `v1.8.1` and `v1.8.2` downloading `v5.0` of the light db. Internally AMRFinderplus `v3.11.26` is used.

```
mamba create -p ./conda-env bakta=1.8.2
mamba activate conda-env
bakta_db download --type light
bakta --db ./db-light/ --verbose --output test GCF_000008865.2.fna.gz
```

Unfortunately, I cannot reproduce this error. Everything was working as expected without any errors at all. Maybe an update of AMRFinder itself might help?

I'd close this for now. But please, do not hesitate to re-open this or opening new issues if this errors occurs on your side with an updated AMRFinder version. And again, thanks for reporting!

**Closed by oschwengers** 2023-10-25 08:36 UTC
Labels: bug
