### ISSUE TITLE
Some annotations in the GFF do not have an ID assigned?

### ISSUE THREAD

**Issue by ZarulHanifah** [oschwengers/bakta#54] opened 2021-05-29 03:57 UTC
**Some annotations don't have an ID in the 9th field**
Majority of the annotations do have ID, but a few don't. I can't use the annotation readily for RNAseq counting using HTSeq. Is this expected?

Here are all of them in one of my annotations without ID (last one is a sample annotation with an ID):

|1|2|3|4|5|6|7|8|9|
|-|-|-|-|-|-|-|-|-|
|HYI41_1|Blast+|oriC|247475|247846|.|?|.|Name=oriC;product=oriC|
|HYI41_1|Infernal|regulatory_region|3904850|3905064|3.4e-39|-|.|Name=rncO;product=rncO;Dbxref=RFAM:RF00552,SO:0005836|
|HYI41_2|Blast+|oriV|3931|4898|.|?|.|Name=oriV;product=oriV|
|HYI41_2|Blast+|oriT|4781|4868|.|?|.|Name=oriT;product=oriT|
|HYI41_1|Prodigal|CDS|2509|3582|.|+|0|ID=EOAEPG_00020;Name=DNA replication and repair protein RecF;locus_tag=EOAEPG_00020;product=DNA replication and repair protein RecF;Dbxref=COG:COG1195,COG:L,GO:0003697,GO:0005524,GO:0005737,GO:0006260,GO:0006281,GO:0009432,RefSeq:WP_000060112.1,SO:0001217,UniParc:UPI000016552D,UniRef100:UniRef100_A7ZTQ6,UniRef50:UniRef50_Q8Z9U9,UniRef90:UniRef90_Q8Z2N4;gene=recF|

**Comment by oschwengers** [comment] 2021-05-31 06:53
Dear @ZarulHanifah ,
thanks for the question and bringing this up. Due to the official GFF3 specification: https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md:
```
ID
Indicates the ID of the feature. The ID attribute is required for features that have children (e.g. gene and mRNAs), or for those that span multiple lines, but are optional for other features. IDs for each feature must be unique within the scope of the GFF file. ...
```

As `oriC`/`oriV`/`oriT` features aren't genes and do not span multiple lines I think that this behavior is in concordance with the `GFF3` spec, so technically it's not a bug. However, it would be absolutely fine and make sense to assign `ID`s if this would help downstream analysis.

Regarding the `regulatory_region` feature you're absolutely right. They are of course part of a particular gene and should be linked to the parent feature via a common `ID`. However, it is not that simple to automatically assign them to a certain CDS. I'll put that on the list and see what we can come up with but that might take a while.

Thanks again - I'll leave this open so that others can relate to this.

**Comment by oschwengers** [comment] 2021-06-30 06:42
@ZarulHanifah This issue should be fixed now. You can install the latest commit version from GitHub via a `pip install <github-repo-path>` or just wait for the next patch release.
Best regards

**Closed by oschwengers** 2021-06-30 06:42 UTC
Labels: enhancement, question
