### ISSUE TITLE
Error in predict_crispr

### ISSUE THREAD

**Issue by abhijeetsingh1704** [oschwengers/bakta#109] opened 2022-05-19 09:17 UTC
**Error in predict_crispr**

Traceback (most recent call last):
  File "/path/.local/bin/bakta", line 8, in <module>
    sys.exit(main())
  File "/path/.local/lib/python3.10/site-packages/bakta/main.py", line 204, in main
    genome['features'][bc.FEATURE_CRISPR] = crispr.predict_crispr(genome, contigs_path)
  File "/path/.local/lib/python3.10/site-packages/bakta/features/crispr.py", line 40, in predict_crispr
    raise Exception(f'PILER-CR error! error code: {proc.returncode}')
Exception: PILER-CR error! error code: -11

**Comment by abhijeetsingh1704** [comment] 2022-05-19 11:26
@oschwengers 
Thanks for the fast reply.
I guess the bug is maybe due to the python update (3.10). It did not happen earlier with python 3.9 or before bakta v1.4.1.
As it was same for multiple genome FNA files, it is not input specific.

Apart from the previous error, there is nothing much in the log file (error below). Looks like there is something in predict_crispr function or **pilercr** and the warnnig is raised by bakta > features > crispr.py line 37-40.

using --skip-crispr did not cause any problem and annotation was sucesful.

I guess it was enough info.

**ERROR**

`11:15:51.670 - DEBUG - MAIN - start CRISPR prediction`
`11:15:51.670 - DEBUG - CRISPR - cmd=['pilercr', '-in', '/tmp/tmp5qs043wz/contigs.fna', '-out', '/tmp/tmp5qs043wz/crispr.txt', '-noinfo', '-quiet']`
`11:15:52.761 - DEBUG - CRISPR - stdout='', stderr=''`
`11:15:52.761 - WARNING - CRISPR - CRISPRs failed! pilercr-error-code=-11`
`11:15:52.775 - INFO - MAIN - removed tmp dir: /tmp/tmp5qs043wz`

**Comment by oschwengers** [comment] 2022-05-19 11:53
Unfortunately, I cannot reproduce this error using a fresh conda environment with Pytthon 3.10.4 and bakta 1.4.1 using the test genome in this repository (test/data/GCF_000008865.2.fna.gz).

Have you tried to execute piler-cr on its own? Would it be possible to provide the genome sequence for debugging purposes?

**Comment by abhijeetsingh1704** [comment] 2022-05-19 12:24
@oschwengers 
Sure, No problem.

* Installed bakta via PIP on python 3.10.4. 
* No virtualizated env.
* Genome file attached
* Error is also attached
* Same error with bakta test file GCF_000008865.2.fna.gz

[Error.txt](https://github.com/oschwengers/bakta/files/8728934/Error.txt)
[GCA_000305935.fna.gz](https://github.com/oschwengers/bakta/files/8728935/GCA_000305935.fna.gz)

**Comment by oschwengers** [comment] 2022-05-19 13:41
Hi @abhijeetsingh1704 ,
I still cannot reproduce this error. Bakta annotated your genome without any issues (log attached).
Could you please provide the actual *.log* file? Otherwise, I'm afraid I cannot help with this.

[GCA_000305935.log.gz](https://github.com/oschwengers/bakta/files/8729599/GCA_000305935.log.gz)

**Comment by oschwengers** [comment] 2022-06-02 13:53
Hi @abhijeetsingh1704 ,
*gentle ping* Is this still active? Any updates on this? Otherwise, I'd close this for now.

**Comment by abhijeetsingh1704** [comment] 2022-06-02 15:34
Hi @oschwengers 
Excuse for not updating. 
But I still have the same problem. 
And I guess it is becuase of pilercr and not because of bakta. Pilercr is giving segmentation fault error and i cant fix it unfortunately. Tried reinstalling as well. So, I just escaped using it as it was not so important.
But any advise would be helpful.

attached the logfile, but it will not give any indication on the error.

[LOGfile.txt](https://github.com/oschwengers/bakta/files/8825337/LOGfile.txt)

**Comment by oschwengers** [comment] 2022-06-03 07:34
Ok, I cannot find anything suspicious here. Since I could annotate the genome you've provided and this clearly seems to be related to PilerCR instead of Bakta, I'm a little bit puzzled.
I'm afraid I cannot do much about this. In this special case, I'd also suggest to just skipt the CRISPR detection via `--skip-crispr` since you mentioned that this is not of any relevance for your analysis.
I'm sorry that I cannot do more about this.

I'll close this for now but please, do not hesitate to re-open it just in case there is any news/update on this that might help to debug it.
Best regards!

**Closed by oschwengers** 2022-06-03 07:34 UTC
Labels: bug
